In [1]:
import sys
import cv2
import numpy as np
import random
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

def imshow(tit, image):
    plt.figure(figsize=(12, 8))
    if len(image.shape) == 3:
        plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    else:
        plt.imshow(image, cmap='gray')
    plt.title(tit)
    plt.axis('off')    
    plt.show()

In [2]:
def hex_to_rgb(hex):
    hlen = len(hex)
    return tuple(int(hex[i:i + hlen // 3], 16) for i in range(0, hlen, hlen // 3))

In [3]:
ctable = pd.read_excel("colortable.xlsx")
print(ctable.tail())
print(len(ctable))

     index     hex
211    212  CCCCCC
212    213  999999
213    214  666666
214    215  333333
215    216  000000
216


In [4]:
r = ctable.hex[0:25]
pd_red = [str(r[i])for i in range(len(r))]

g = pd.DataFrame(ctable.hex[43:129]).reset_index()
pd_green = [str(g.hex[i])for i in range(len(g))]

p = pd.DataFrame(ctable.hex[152:210]).reset_index()
pd_purple = [str(p.hex[i])for i in range(len(p))]

In [6]:
pd_green_rgb = []
pd_green_hsv = []

for i,v in enumerate(pd_green):
    rgb = hex_to_rgb(v)
    
    color = rgb
    pixel = np.uint8([[color]])
    
    hsv = cv2.cvtColor(pixel, cv2.COLOR_BGR2HSV)
    hsv = hsv[0][0]
    print(i+44, 'rgb:',rgb,'-> hsv:', hsv)
    
    pd_green_rgb.append(rgb)
    pd_green_hsv.append(hsv)

44 rgb: (204, 204, 153) -> hsv: [ 90  64 204]
45 rgb: (153, 153, 102) -> hsv: [ 90  85 153]
46 rgb: (102, 102, 51) -> hsv: [ 90 128 102]
47 rgb: (51, 51, 0) -> hsv: [ 90 255  51]
48 rgb: (204, 204, 102) -> hsv: [ 90 128 204]
49 rgb: (153, 153, 51) -> hsv: [ 90 170 153]
50 rgb: (102, 102, 0) -> hsv: [ 90 255 102]
51 rgb: (204, 204, 51) -> hsv: [ 90 191 204]
52 rgb: (204, 204, 0) -> hsv: [ 90 255 204]
53 rgb: (153, 153, 0) -> hsv: [ 90 255 153]
54 rgb: (204, 255, 102) -> hsv: [ 80 153 255]
55 rgb: (204, 255, 51) -> hsv: [ 82 204 255]
56 rgb: (204, 255, 0) -> hsv: [ 84 255 255]
57 rgb: (153, 204, 51) -> hsv: [ 80 191 204]
58 rgb: (153, 204, 0) -> hsv: [ 82 255 204]
59 rgb: (102, 153, 0) -> hsv: [ 80 255 153]
60 rgb: (153, 204, 102) -> hsv: [ 75 128 204]
61 rgb: (102, 153, 51) -> hsv: [ 75 170 153]
62 rgb: (51, 102, 0) -> hsv: [ 75 255 102]
63 rgb: (153, 255, 0) -> hsv: [ 78 255 255]
64 rgb: (102, 204, 51) -> hsv: [ 70 191 204]
65 rgb: (102, 204, 0) -> hsv: [ 75 255 204]
66 rgb: (51, 153, 

In [7]:
pd_green_hsv

[array([ 90,  64, 204], dtype=uint8),
 array([ 90,  85, 153], dtype=uint8),
 array([ 90, 128, 102], dtype=uint8),
 array([ 90, 255,  51], dtype=uint8),
 array([ 90, 128, 204], dtype=uint8),
 array([ 90, 170, 153], dtype=uint8),
 array([ 90, 255, 102], dtype=uint8),
 array([ 90, 191, 204], dtype=uint8),
 array([ 90, 255, 204], dtype=uint8),
 array([ 90, 255, 153], dtype=uint8),
 array([ 80, 153, 255], dtype=uint8),
 array([ 82, 204, 255], dtype=uint8),
 array([ 84, 255, 255], dtype=uint8),
 array([ 80, 191, 204], dtype=uint8),
 array([ 82, 255, 204], dtype=uint8),
 array([ 80, 255, 153], dtype=uint8),
 array([ 75, 128, 204], dtype=uint8),
 array([ 75, 170, 153], dtype=uint8),
 array([ 75, 255, 102], dtype=uint8),
 array([ 78, 255, 255], dtype=uint8),
 array([ 70, 191, 204], dtype=uint8),
 array([ 75, 255, 204], dtype=uint8),
 array([ 70, 255, 153], dtype=uint8),
 array([ 75, 102, 255], dtype=uint8),
 array([ 75, 204, 255], dtype=uint8),
 array([ 67, 204, 255], dtype=uint8),
 array([ 67,